name: build

on: [push, pull_request]

jobs:
    run:
        runs-on: ${{ matrix.operating-system }}

        strategy:
            fail-fast: false
            matrix:
                operating-system: ['ubuntu-latest']
                php-versions:
                    - '7.2'
                    - '7.1'
                    - '7.0'
                    - '5.6'
                    - '5.5'
                    - '5.4'
                    - '5.3'

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: mbstring, intl, dom
                  ini-values: max_execution_time=0
                  coverage: xdebug

            - name: Setup PHP_VERSION env variable
              run: |
                  echo PHP_VERSION=$(echo "<?php echo join('.', array_slice(explode('.', PHP_VERSION), 0, 2)); " | php) >> $GITHUB_ENV

            - name: Install dependencies
              run: |
                  echo PHP_VERSION: ${{ env.PHP_VERSION }}
                  composer install

            - name: Run tests
              run: |
                  mkdir -p build/logs
                  COMPOSER_PROCESS_TIMEOUT=0 composer test
